[Pairs]
update frequency price: 5
# seconds, how often pair prices should be updated
update frequency instruments info: 60
# seconds, how often instruments info should be updated

[Spike detector]
max range: 30
# integer, in minutes, range where spike search happens
cooldown: 30
# in minutes

[Chart]
timezone: UTC
# should be one of IANA timezones: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
